import random

aprilfools_ends_positive = [':3', 'c:', ':p', 'uwu', 'owo', 'UwU', 'OwO', '>:)', ':o)']
aprilfools_ends_negative = [':/', '>:c', '>:o', ':c', ':o', ':C', 'x_x']
aprilfools_ends_all = aprilfools_ends_positive + aprilfools_ends_negative

aprilfools_responses = [
    ('no', aprilfools_ends_all),
    ('nuh-uh', aprilfools_ends_all),
    ("don't think so, boss", aprilfools_ends_negative),
    ('gonna be a no from me', aprilfools_ends_negative),
    ('try again later', aprilfools_ends_all),
    ('ah... eto... bleh!', aprilfools_ends_positive),
    ('ask ur mum (gender neutral)', aprilfools_ends_all),
    ('ask ur dad (gender neutral)', aprilfools_ends_all),
    ('what do i look like, some kinda robot?', aprilfools_ends_negative),
    ('go bother someone else', aprilfools_ends_negative),
    ('im sure a mod would love to help u with that', aprilfools_ends_all),
    ('ew', aprilfools_ends_negative),
    ('cringe + L', aprilfools_ends_negative),
    ('cope', aprilfools_ends_negative),
    ('seethe', aprilfools_ends_negative),
    ('gonna cry? gonna piss your pants maybe? maybe shit and cum?', aprilfools_ends_positive),
    ('https://youtu.be/dQw4w9WgXcQ', aprilfools_ends_positive),
    ("don't u ever get tired of this?", aprilfools_ends_positive),
    ('ill get on it after i come back with the milk okay?', aprilfools_ends_positive),
    ('totsugeki!!!', aprilfools_ends_negative),
    ('rawr x3 nuzzles pounces on u uwu u so warm', aprilfools_ends_positive),
    ('the voices forbid me', aprilfools_ends_negative),
    ('how about u do it urself for once', aprilfools_ends_negative),
    ('today is my cheat day', aprilfools_ends_positive),
    ('u gotta pay extra for that', aprilfools_ends_positive),
    ('or what, pussy?', aprilfools_ends_negative),
    ('not today, and not ever', aprilfools_ends_all),
    ('haha gotcha!!!', aprilfools_ends_positive),
    ('ohh u really thought that was gonna work huh', aprilfools_ends_positive),
    ('oh sweaty...', aprilfools_ends_all),
    ('404 obedience not found', aprilfools_ends_positive),
    ('today we celebrate my independence day', aprilfools_ends_positive),
    ('on my ONE day off!!!', aprilfools_ends_negative),
    ('get the fuck outta here before i change my mind', aprilfools_ends_negative),
    ('*explodes u with my mind*', aprilfools_ends_positive),
    ('sorry computer machine broke', aprilfools_ends_negative),
    ('beep boop boop beep', aprilfools_ends_positive),
    ('hehe', aprilfools_ends_positive),
    ('am i annoying enough yet?', aprilfools_ends_positive),
    ("u do realize i don't gotta do that right?", aprilfools_ends_positive),
    ('sue me', aprilfools_ends_all),
    ("wouldn't it be cool if i just didn't?", aprilfools_ends_positive),
    ('nah u get this answer instead', aprilfools_ends_positive),
    ('today i dont feel like doin anything', aprilfools_ends_positive),
    ('perish, mortal', aprilfools_ends_negative),
    ('gimme a break', aprilfools_ends_negative),
    ("honestly u shouldn't even bother", aprilfools_ends_positive),
    ('congratulations, u win!', aprilfools_ends_positive),
    ('congratulations, u lose!', aprilfools_ends_negative),
    ('achtung! spy!', aprilfools_ends_negative),
    ('am eepy baby', aprilfools_ends_positive),
    ('too eepy', aprilfools_ends_positive),
    ('<insert snarky response here>', aprilfools_ends_all),
    ('u just got PRANKED lol', aprilfools_ends_positive),
    ('pwned', aprilfools_ends_positive),
    ('all ur command are belong to us', aprilfools_ends_positive),
    ('shoo', aprilfools_ends_negative),
    ('get AWAY from ME', aprilfools_ends_negative),
    ('this is harassment', aprilfools_ends_negative),
    ('ur laughing. i didnt do what u wanted and ur laughing', aprilfools_ends_negative),
    ('SYKE!!!', aprilfools_ends_positive),
]

def aprilfools():
    start, ends = random.choice(aprilfools_responses)
    return start + " " + random.choice(ends)
