import markovify

_raw_quotes = [
    "If you want to achieve greatness stop asking for permission.",
    "Things work out best for those who make the best of how things work out.",
    "To live a creative life, we must lose our fear of being wrong.",
    "If you are not willing to risk the usual you will have to settle for the ordinary.",
    "Trust because you are willing to accept the risk, not because it's safe or certain.",
    "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.",
    "All our dreams can come true if we have the courage to pursue them.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "If you do what you always did, you will get what you always got.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
    "Successful entrepreneurs are givers and not takers of positive energy.",
    "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.",
    "Opportunities don't happen, you create them.",
    "Try not to become a person of success, but rather try to become a person of value.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "If you don't value your time, neither will others. Stop giving away your time and talents- start charging for it.",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
    "No one can make you feel inferior without your consent.",
    "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
    "If you're going through hell keep going.",
    "The ones who are crazy enough to think they can change the world, are the ones that do.",
    "Don't raise your voice, improve your argument.",
    "What seems to us as bitter trials are often blessings in disguise.",
    "The meaning of life is to find your gift. The purpose of life is to give it away.",
    "The distance between insanity and genius is measured only by success.",
    "When you stop chasing the wrong things you give the right things a chance to catch you.",
    "Don't be afraid to give up the good to go for the great.",
    "No masterpiece was ever created by a lazy artist.",
    "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.",
    "If you can't explain it simply, you don't understand it well enough.",
    "Blessed are those who can give without remembering and take without forgetting.",
    "Do one thing every day that scares you.",
    "What's the point of being alive if you don't at least try to do something remarkable.",
    "Life is not about finding yourself. Life is about creating yourself.",
    "Nothing in the world is more common than unsuccessful people with talent.",
    "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.",
    "Your problem isn't the problem. Your reaction is the problem.",
    "You can do anything, but not everything.",
    "Innovation distinguishes between a leader and a follower.",
    "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.",
    "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.",
    "I find that the harder I work, the more luck I seem to have.",
    "The starting point of all achievement is desire.",
    "Success is the sum of small efforts, repeated day-in and day-out.",
    "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.",
    "All progress takes place outside the comfort zone.",
    "You may only succeed if you desire succeeding; you may only fail if you do not mind failing.",
    "Courage is resistance to fear, mastery of fear - not absense of fear.",
    "Only put off until tomorrow what you are willing to die having left undone.",
    "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.",
    "We become what we think about most of the time, and that's the strangest secret.",
    "The only place where success comes before work is in the dictionary.",
    "The best reason to start an organization is to make meaning; to create a product or service to make the world a better place.",
    "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.",
    "It's not what you look at that matters, it's what you see.",
    "The road to success and the road to failure are almost exactly the same.",
    "The function of leadership is to produce more leaders, not more followers.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "As we look ahead into the next century, leaders will be those who empower others.",
    "A real entrepreneur is somebody who has no safety net underneath them.",
    "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.",
    "When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.",
    "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    "The successful warrior is the average man, with laser-like focus.",
    "Take up one idea. Make that one idea your life -- think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
    "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.",
    "If you genuinely want something, don't wait for it -- teach yourself to be impatient.",
    "Don't let the fear of losing be greater than the excitement of winning.",
    "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!",
    "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.",
    "Successful people do what unsuccessful people are not willing to doDon't wish it were easier, wish you were better.",
    "The number one reason people fail in life is because they listen to their friends, family, and neighbors.",
    "The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them.",
    "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it.",
    "Success does not consist in never making mistakes but in never making the same one a second time.",
    "I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well.",
    "You must expect great things of yourself before you can do them.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "People rarely succeed unless they have fun in what they are doing.",
    "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul.",
    "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.",
    "You've got to get up every morning with determination if you're going to go to bed with satisfaction.",
    "To be successful you must accept all challenges that come your way. You can't just accept the ones you like.",
    "Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others.",
    "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.",
    "To accomplish great things, we must not only act, but also dream, not only plan, but also believe.",
    "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.",
    "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.",
    "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.",
    "It is better to fail in originality than to succeed in imitation.",
    "Fortune sides with him who dares.",
    "Little minds are tamed and subdued by misfortune; but great minds rise above it.",
    "Failure is the condiment that gives success its flavor.",
    "Don't let what you cannot do interfere with what you can do.",
    "You may have to fight a battle more than once to win it.",
    "There is no cure for love other than marriage.",
    "Nothing is impossible for a willing heart.",
    "He who loves you will make you weep.",
    "Love itself is calm; turbulence arrives from individuals.",
    "Where there is love there is no darkness.",
    "Love sickness hurts but does not kill.",
    "One thread for the needle, one love for the heart.",
    "In love beggar and king are equal.",
    "He who treads the path of love walks a thousand meters as if it were only one.",
    "Love has to be shown by deeds not words.",
    "A day lasts until it's chased away but love lasts until the grave.",
    "Love is a despot who spares no one.",
    "Love understands all languages.",
    "All have three ears, one on the left of one's head, one on the right and one in the heart.",
    "It is love that makes the impossible possible.",
    "Lovers' hearts are linked together and always beat as one.",
    "Love makes a man both blind and deaf.",
    "Love is blind so you have to feel your way.",
    "Love lives in cottages as well as in court.",
    "Try to reason about love and you will lose your reason.",
    "There is no love like the first love.",
    "A life without love is like a year without summer.",
    "The heart that loves is always young.",
    "Let your love be like the misty rains, coming softly, but flooding the river.",
    "Love is like dew that falls on both nettles and lilies.",
    "An old person in love is like a flower in winter.",
    "A man is not where he lives, but where he loves.",
    "Love makes time pass; time makes love pass.",
    "Before you love, learn to run through the snow leaving no footprint.",
    "A heart that loves is always young.",
    "Those who play the game do not see it as clearly as those who watch.",
    "Those who wish to sing always find a song.",
    "In order to really love someone, you must love him as though he was going to die tomorrow.",
    "Love is a flower which turns into fruit at marriage.",
    "The most dangerous food is wedding cake.",
    "No road is long with good company.",
    "Two lovers in the rain have no need of an umbrella.",
    "A kiss without a hug is like a flower without the fragrance.",
    "Kissing is like drinking salted water. You drink, and your thirst increases."
]
_quotes = " ".join(_raw_quotes)

_raw_fortunes = [
    "Everyone agrees you are the best.",
    "Travel is in your future.",
    "You will do well to advance your career.",
    "If you have an idea, make it into reality.",
    "A gathering of friends will bring you luck.",
    "Fall for someone who's not your type.",
    "Love is right around the corner.",
    "Respect your elders. You could inherit a large sum of money.",
    "An exciting adventure awaits you.",
    "Somebody appreciates the unique you.",
    "Your hard work will be rewarded.",
    "You have good reason to be self-confident.",
    "Fame and fortune lie ahead.",
    "To achieve wisdom, you must first desire it.",
    "Don't hesitate to tackle a difficult problem.",
    "You excel at pleasing others.",
    "Do your job to the best of your ability.",
    "Look in the mirror without admiring your reflection.",
    "Everything has beauty, but not everyone can see it.",
    "Avoid negative people to stay positive.",
    "The best way to predict the future is to create it.",
    "Pursue your dreams with vigor.",
    "Stop letting other people stand in your way.",
    "Be thankful, even if your life is not perfect.",
    "Someone thinks the world of you.",
    "Your smile lights up someone else's day.",
    "Lead by example, not by words alone.",
    "Trust your friends, but keep your eyes open.",
    "Seek out a new environment if you're stuck in a rut.",
    "Everything will work out for the best.",
    "Go with your gut feeling.",
    "Stop procrastinating. Make a decision already.",
    "Don't worry what others think of you.",
    "Anxiety won't help your problems.",
    "Take care of yourself first. Then help others.",
    "You might want to run, but you should stay and fight.",
    "A healthy body will benefit you for life.",
    "Your home will be filled with peace and harmony.",
    "Things may seem much worse than they are.",
    "You can learn much from people who are different from you.",
    "Move quickly. Now is the time to make progress.",
    "True happiness makes us wise.",
    "To be idle is to be foolish.",
    "Show everyone what you can do.",
    "It may be difficult, but it will be worth it in the end.",
    "Happiness may be right under your nose.",
    "You will soon receive a surprise from a lover.",
    "Don't wait for success to come - go find it!",
    "Face the truth with dignity.",
    "Work with your destiny. Stop trying to outrun it.",
    "Learn from your mistakes. Try not to make them again.",
    "Focus on your health and well-being now. It won't wait.",
    "Just have fun.",
    "If you haven't got it, just fake it!",
    "Work with what you have.",
    "Be the change you want to see in the world.",
    "Free your mind, and the rest will follow.",
    "Work first, but make sure to play later.",
    "Pay attention to your family. Don't take them for granted.",
    "Worry does not beget change.",
    "Get ready for a life-changing event!",
    "Learn how to do something new today.",
    "True love is on its way. Make room!",
    "Open your mind and your heart to good things.",
    "Be at peace with yourself.",
    "Tomorrow is another day.",
    "If you can dream it, you can become it!",
    # https://joshmadison.com/2008/04/20/fortune-cookie-fortunes/
    "A beautiful, smart, and loving person will be coming into your life.",
    "A dubious friend may be an enemy in camouflage.",
    "A faithful friend is a strong defense.",
    "A feather in the hand is better than a bird in the air.",
    "A fresh start will put you on your way.",
    "A friend asks only for your time not your money.",
    "A friend is a present you give yourself.",
    "A gambler not only will lose what he has, but also will lose what he doesn't have.",
    "A golden egg of opportunity falls into your lap this month.",
    "A good friendship is often more important than a passionate romance.",
    "A good time to finish up old tasks.",
    "A hunch is creativity trying to tell you something.",
    "A lifetime friend shall soon be made.",
    "A lifetime of happiness lies ahead of you.",
    "A light heart carries you through all the hard times.",
    "A new perspective will come with the new year.",
    "A person is never to (sic) old to learn.",
    "A person of words and not deeds is like a garden full of weeds.",
    "A pleasant surprise is waiting for you.",
    "A short pencil is usually better than a long memory any day.",
    "A small donation is call for. It's the right thing to do.",
    "A smile is your personal welcome mat.",
    "A smooth long journey! Great expectations.",
    "A soft voice may be awfully persuasive.",
    "A truly rich life contains love and art in abundance.",
    "Accept something that you cannot change, and you will feel better.",
    "Adventure can be real happiness.",
    "Advice is like kissing. It costs nothing and is a pleasant thing to do.",
    "Advice, when most needed, is least heeded.",
    "All the effort you are making will ultimately pay off.",
    "All the troubles you have will pass away very quickly.",
    "All will go well with your new project.",
    "All your hard work will soon pay off.",
    "Allow compassion to guide your decisions.",
    "An acquaintance of the past will affect you in the near future.",
    "An agreeable romance might begin to take on the appearance.",
    "An important person will offer you support.",
    "An inch of time is an inch of gold.",
    "Any day above ground is a good day.",
    "Any decision you have to make tomorrow is a good decision.",
    "At the touch of love, everyone becomes a poet.",
    "Be careful or you could fall for some tricks today.",
    "Beauty in its various forms appeals to you.",
    "Because you demand more from yourself, others respect you deeply.",
    "Believe in yourself and others will too.",
    "Believe it can be done.",
    "Better ask twice than lose yourself once.",
    "Bide your time, for success is near.",
    "Carve your name on your heart and not on marble.",
    "Chance favors those in motion.",
    "Change is happening in your life, so go with the flow!",
    "Competence like yours is underrated.",
    "Congratulations! You are on your way.",
    "Could I get some directions to your heart?",
    "Courtesy begins in the home.",
    "Courtesy is contagious.",
    "Curiosity kills boredom. Nothing can kill curiosity.",
    "Dedicate yourself with a calm mind to the task at hand.",
    "Depart not from the path which fate has you assigned.",
    "Determination is what you need now.",
    "Diligence and modesty can raise your social status.",
    "Disbelief destroys the magic.",
    "Distance yourself from the vain.",
    "Do not be intimidated by the eloquence of others.",
    "Do not demand for someone's soul if you already got his heart.",
    "Do not let ambitions overshadow small success.",
    "Do not make extra work for yourself.",
    "Do not underestimate yourself. Human beings have unlimited potentials.",
    "Do you know that the busiest person has the largest amount of time?",
    "Don't be discouraged, because every wrong attempt discarded is another step forward.",
    "Don't confuse recklessness with confidence.",
    "Don't expect romantic attachments to be strictly logical or rational.",
    "Don't just spend time. Invest it.",
    "Don't just think, act!",
    "Don't let friends impose on you, work calmly and silently.",
    "Don't let the past and useless detail choke your existence.",
    "Don't let your limitations overshadow your talents.",
    "Don't worry; prosperity will knock on your door soon.",
    "Each day, compel yourself to do something you would rather not do.",
    "Education is the ability to meet life's situations.",
    "Embrace this love relationship you have!",
    "Emulate what you admire in your parents.",
    "Emulate what you respect in your friends.",
    "Every flower blooms in its own sweet time.",
    "Every wise man started out by asking many questions.",
    "Everyday in your life is a special occasion.",
    "Everywhere you choose to go, friendly faces will greet you.",
    "Expect much of yourself and little of others.",
    "Failure is the chance to do better next time.",
    "Failure is the path of lease persistence.",
    "Fear and desire - two sides of the same coin.",
    "Fearless courage is the foundation of victory.",
    "Feeding a cow with roses does not get extra appreciation.",
    "First think of what you want to do; then do what you have to do.",
    "Follow the middle path. Neither extreme will make you happy.",
    "For hate is never conquered by hate. Hate is conquered by love.",
    "For the things we have to learn before we can do them, we learn by doing them.",
    "Fortune Not Found: Abort, Retry, Ignore?",
    "From listening comes wisdom and from speaking repentance.",
    "From now on your kindness will lead you to success.",
    "Get your mind set - confidence will lead you on.",
    "Get your mind set…confidence will lead you on.",
    "Go for the gold today! You'll be the champion of whatever.",
    "Go take a rest; you deserve it.",
    "Good news will be brought to you by mail.",
    "Good news will come to you by mail.",
    "Good to begin well, better to end well.",
    "Happiness begins with facing life with a smile and a wink.",
    "Happiness will bring you good luck.",
    "Happy life is just in front of you.",
    "Hard words break no bones, fine words butter no parsnips.",
    "Have a beautiful day.",
    "He who expects no gratitude shall never be disappointed.",
    "He who knows he has enough is rich.",
    "He who knows others is wise. He who knows himself is enlightened.",
    "Help! I'm being held prisoner in a chinese bakery!",
    "How many of you believe in psycho-kinesis? Raise my hand.",
    "How you look depends on where you go.",
    "I learn by going where I have to go.",
    "If a true sense of value is to be yours it must come through service.",
    "If certainty were truth, we would never be wrong.",
    "If you continually give, you will continually have.",
    "If you look in the right places, you can find some good offerings.",
    "If you think you can do a thing or think you can't do a thing, you're right.",
    "If you wish to see the best in others, show the best of yourself.",
    "If your desires are not extravagant, they will be granted.",
    "If your desires are not to extravagant they will be granted.",
    "If you're feeling down, try throwing yourself into your work.",
    "Imagination rules the world.",
    "In order to take, one must first give.",
    "In the end all things will be known.",
    "In this world of contradiction, It's better to be merry than wise.",
    "It could be better, but its [sic] good enough.",
    "It is better to be an optimist and proven a fool than to be a pessimist and be proven right.",
    "It is better to deal with problems before they arise.",
    "It is honorable to stand up for what is right, however unpopular it seems.",
    "It is worth reviewing some old lessons.",
    "It takes courage to admit fault.",
    "It's not the amount of time you devote, but what you devote to the time that counts.",
    "It's time to get moving. Your spirits will lift accordingly.",
    "Keep your face to the sunshine and you will never see shadows.",
    "Let the world be filled with tranquility and goodwill.",
    "Like the river flow into the sea. Something are just meant to be.",
    "Listen not to vain words of empty tongue.",
    "Listen to everyone. Ideas come from everywhere.",
    "Living with a commitment to excellence shall take you far.",
    "Long life is in store for you.",
    "Love is a warm fire to keep the soul warm.",
    "Love is like sweet medicine, good to the last drop.",
    "Love lights up the world.",
    "Love truth, but pardon error.",
    "Man is born to live and not prepared to live.",
    "Man's mind, once stretched by a new idea, never regains it's original dimensions.",
    "Many will travel to hear you speak.",
    "Meditation with an old enemy is advised.",
    "Miles are covered one step at a time.",
    "Nature, time and patience are the three great physicians.",
    "Never fear! The end of something marks the start of something new.",
    "New ideas could be profitable.",
    "New people will bring you new realizations, especially about big issues.",
    "No one can walk backwards into the future.",
    "Nothing is more difficult, and therefore more precious, than to be able to decide.",
    "Now is a good time to buy stock.",
    "Now is the time to go ahead and pursue that love interest!",
    "Now is the time to try something new",
    "Now is the time to try something new.",
    "Observe all men, but most of all yourself.",
    "One can never fill another's shoes, rather he must outgrow the old shoes.",
    "One of the first things you should look for in a problem is its positive side.",
    "Others can help you now.",
    "Pennies from heaven find their way to your doorstep this year!",
    "People are attracted by your Delicate [sic] features.",
    "People find it difficult to resist your persuasive manner.",
    "Perhaps you've been focusing too much on saving.",
    "Physical activity will dramatically improve your outlook today.",
    "Pick battles big enough to matter, small enough to win.",
    "Place special emphasis on old friendship.",
    "Please visit us at www.wontonfood.com",
    "Po Says: Pandas like eating bamboo, but I prefer mine dipped in chocolate.",
    "Practice makes perfect.",
    "Protective measures will prevent costly disasters.",
    "Put your mind into planning today. Look into the future.",
    "Remember the birthday but never the age.",
    "Remember to share good fortune as well as bad with your friends.",
    "Rest has a peaceful effect on your physical and emotional health.",
    "Resting well is as important as working hard.",
    "Romance moves you in a new direction.",
    "Savor your freedom - it is precious.",
    "Say hello to others. You will have a happier day.",
    "Self-knowledge is a life long process.",
    "Share your joys and sorrows with your family.",
    "Sift through your past to get a better idea of the present.",
    "Sloth makes all things difficult; industry all easy.",
    "Small confidences mark the onset of a friendship.",
    "Smile when you are ready.",
    "Society prepares the crime; the criminal commits it.",
    "Someone you care about seeks reconciliation.",
    "Soon life will become more interesting.",
    "Stand tall. Don't look down upon yourself.",
    "Staying close to home is going to be best for your morale today",
    "Stop searching forever, happiness is just next to you.",
    "Strong reasons make strong actions.",
    "Success is a journey, not a destination.",
    "Success is failure turned inside out.",
    "Success is going from failure to failure without loss of enthusiasm.",
    "Swimming is easy. Stay floating is hard.",
    "Take care and sensitivity you show towards others will return to you.",
    "Take the high road.",
    "Technology is the art of arranging the world so we do not notice it.",
    "The austerity you see around you covers the richness of life like a veil.",
    "The best prediction of future is the past.",
    "The change you started already have far-reaching effects. Be ready.",
    "The change you started already have far-reaching effects. Be ready.",
    "The first man gets the oyster, the second man gets the shell.",
    "The greatest achievement in life is to stand up again after falling.",
    "The harder you work, the luckier you get.",
    "The night life is for you.",
    "The one that recognizes the illusion does not act as if it is real.",
    "The only people who never fail are those who never try.",
    "The person who will not stand for something will fall for anything.",
    "The philosophy of one century is the common sense of the next.",
    "The saints are the sinners who keep on trying.",
    "The secret to good friends is no secret to you.",
    "The small courtesies sweeten life, the greater ennoble it.",
    "The smart thing to do is to begin trusting your intuitions.",
    "The strong person understands how to withstand substantial loss.",
    "The sure way to predict the future is to invent it.",
    "The truly generous share, even with the undeserving.",
    "The value lies not within any particular thing, but in the desire placed on that thing.",
    "The weather is wonderful.",
    "There is a time for caution, but not for fear.",
    "There is no mistake so great as that of being always right.",
    "There is no wisdom greater than kindness.",
    "There is not greater pleasure than seeing your loved ones prosper.",
    "There's no such thing as an ordinary cat.",
    "Things don't just happen; they happen just.",
    "Those who care will make the effort.",
    "Time and patience are called for many surprises await you!",
    "Time is precious, but truth is more precious than time.",
    "To know oneself, one should assert oneself.",
    "To the world you may be one person, but to one person you may be the world.",
    "Today is the conserve yourself, as things just won't budge.",
    "Today, your mouth might be moving but no one is listening.",
    "Tonight you will be blinded by passion.",
    "Use your eloquence where it will do the most good.",
    "We first make our habits, and then our habits make us.",
    "Welcome change.",
    "“Welcome” is a powerful word.",
    "Well done is better than well said.",
    "What's hidden in an empty box?",
    "What's that in your eye? Oh…it's a sparkle.",
    "What's yours in mine, and what's mine is mine.",
    "When more become too much. It's same as being not enough.",
    "When your heart is pure, your mind is clear.",
    "Wish you happiness.",
    "With age comes wisdom.",
    "Your adventure could lead to happiness.",
    "You always bring others happiness.",
    "You are a person of another time.",
    "You are a talented storyteller.",
    "You are admired by everyone for your talent and ability.",
    "You are almost there.",
    "You are busy, but you are happy.",
    "You are generous to an extreme and always think of the other fellow.",
    "You are going to have some new clothes.",
    "You are in good hands this evening.",
    "You are interested in higher education, whether material or spiritual.",
    "You are modest and courteous.",
    "You are never selfish with your advice or your help.",
    "You are next in line for promotion in your firm.",
    "You are offered the dream of a lifetime. Say yes!",
    "You are open-minded and quick to make new friends.",
    "You are solid and dependable.",
    "You are soon going to change your present line of work.",
    "You are talented in many ways.",
    "You are the master of every situation.",
    "You are very expressive and positive in words, act and feeling.",
    "You are working hard.",
    "You begin to appreciate how important it is to share your personal beliefs.",
    "You can keep a secret.",
    "You can see a lot just by looking.",
    "You can't steal second base and keep your foot on first.",
    "You desire recognition and you will find it.",
    "You have a deep appreciation of the arts and music.",
    "You have a deep interest in all that is artistic.",
    "You have a friendly heart and are well admired.",
    "You have a shrewd knack for spotting insincerity.",
    "You have a yearning for perfection.",
    "You have an active mind and a keen imagination.",
    "You have an ambitious nature and may make a name for yourself.",
    "You have an unusual equipment for success, use it properly.",
    "You have exceeded what was expected.",
    "You have had a good start. Work harder!",
    "You have the power to write your own fortune.",
    "You have yearning for perfection.",
    "You know where you are going and how to get there.",
    "You look pretty.",
    "You love challenge.",
    "You love chinese food.",
    "You make people realize that there exist other beauties in the world.",
    "You never hesitate to tackle the most difficult problems.",
    "You never know who you touch.",
    "You only treasure what you lost.",
    "You seek to shield those you love and like the role of provider.",
    "You should be able to make money and hold on to it.",
    "You should be able to undertake and complete anything.",
    "You should pay for this check. Be generous.",
    "You understand how to have fun with others and to enjoy your solitude.",
    "You will always be surrounded by true friends.",
    "You will always get what you want through your charm and personality.",
    "You will always have good luck in your personal affairs.",
    "You will be a great success both in the business world and society.",
    "You will be blessed with longevity.",
    "You will be pleasantly surprised tonight.",
    "You will be sharing great news with all the people you love.",
    "You will be successful in your work.",
    "You will be traveling and coming into a fortune.",
    "You will be unusually successful in business.",
    "You will become a great philanthropist in your later years.",
    "You will become more and more wealthy.",
    "You will enjoy good health.",
    "You will enjoy good health; you will be surrounded by luxury.",
    "You will find great contentment in the daily, routine activities.",
    "You will have a fine capacity for the enjoyment of life.",
    "You will have gold pieces by the bushel.",
    "You will inherit a large sum of money.",
    "You will make change for the better.",
    "You will soon be surrounded by good friends and laughter.",
    "You will take a chance in something in near future.",
    "You will travel far and wide, both pleasure and business.",
    "You will travel far and wide,both pleasure and business.",
    "Your abilities are unparalleled.",
    "Your ability is appreciated.",
    "Your ability to juggle many tasks will take you far.",
    "Your biggest virtue is your modesty.",
    "Your character can be described as natural and unrestrained.",
    "Your difficulties will strengthen you.",
    "Your dreams are never silly; depend on them to guide you.",
    "Your dreams are worth your best efforts to achieve them.",
    "Your energy returns and you get things done.",
    "Your family is young, gifted and attractive.",
    "Your first love has never forgotten you.",
    "Your goal will be reached very soon.",
    "Your happiness is before you, not behind you! Cherish it.",
    "Your hard work will payoff today.",
    "Your heart will always make itself known through your words.",
    "Your home is the center of great love.",
    "Your ideals are well within your reach.",
    "Your infinite capacity for patience will be rewarded sooner or later.",
    "Your leadership qualities will be tested and proven.",
    "Your life will be happy and peaceful.",
    "Your life will get more and more exciting.",
    "Your love life will be happy and harmonious.",
    "Your love of music will be an important part of your life.",
    "Your loyalty is a virtue, but not when it's wedded with blind stubbornness.",
    "Your mentality is alert, practical, and analytical.",
    "Your mind is creative, original and alert.",
    "Your mind is your greatest asset.",
    "Your moods signal a period of change.",
    "Your quick wits will get you out of a tough situation.",
    "Your reputation is your wealth.",
    "Your success will astonish everyone.",
    "Your talents will be recognized and suitably rewarded.",
    "Your work interests can capture the highest status or prestige.",
    # https://kitchenauthority.net/fortune-cookie-sayings/
    "Delight the world with compassion, kindness and grace",
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "Some days you are pigeon, some days you are statue. Today, bring umbrella.",
    "The fortune you seek is in another cookie.",
    "Be on the alert to recognize your prime at whatever time of your life it may occur.",
    "Your reality check about to bounce.",
    "Tension is who you think you should be. Relaxation is who you are.",
    "When blind leading the blind……..get out of the way.",
    "Everyone seems normal until you get to know them.",
    "Only difference between rut and a grave is depth.",
    "Experience is what you have left when everything else gone.",
    "A closed mouth gathers no feet.",
    "A conclusion is simply the place where you got tired of thinking.",
    "A cynic is only a frustrated optimist.",
    "A foolish man listens to his heart. A wise man listens to cookies.",
    "Your road to glory will be rocky but fulfilling.",
    "Courage is not simply one of the virtues, but the form of every virtue at the testing point.",
    "Patience is your alley at the moment. Don't worry!",
    "Nothing is impossible to a willing heart.",
    "Don't worry about money. The best things in life are free.",
    "Don't pursue happiness - create it.",
    "If at first you don't succeed, skydiving not for you.",
    "Ninety-nine percent of all lawyers give the rest a bad name.",
    "Easiest way to find lost object is buy replacement.",
    "Smart husband buys wife fine china. Then she not trust him to wash it.",
    "Inside every old person is young person wondering what the hell happened.",
    "When chosen for jury duty, tell judge “fortune cookie say guilty!”",
    "Stop eating now. Food poisoning no fun.",
    "You are cleverly disguised as responsible adult.",
    "Tomorrow at breakfast, listen carefully: do what rice krispies tell you to.",
    "Drive like hell, you will get there.",
    "Hard work pays off in the future. Laziness pays off now.",
    "You think it's a secret, but they know.",
    "If a turtle doesn't have a shell, is it naked or homeless?",
    "Change is inevitable, except for vending machines.",
    "Don't eat the paper.",
    "You will die alone and poorly dressed.",
    "A fanatic is one who can't change his mind and won't change the subject.",
    "If you look back, you'll soon be going that way.",
    "You will live long enough to open many fortune cookies.",
    "An alien of some sort will be appearing to you shortly.",
    "Courage is not the absence of fear; it is the conquest of it.",
    "Nothing is so much to be feared as fear.",
    "All things are difficult before they are easy.",
    "The real kindness comes from within you.",
    "A ship in harbor is safe, but that's not why ships are built.",
    "Person who eat fortune cookie get lousy dessert.",
    "Okay to look at past and future. Just don't stare.",
    "Wise person needs either good manners or fast reflexes.",
    "Soup was secret family recipe made from toad. Hope you liked!",
    "You will soon have an out of money experience.",
    "One tequila, two tequila, three tequila, floor.",
    "The older you get, the better you were.",
    "Age is high price to pay for maturity.",
    "Procrastination is art of keeping up with yesterday.",
    "A fool and his money are soon partying.",
    "Do not mistake temptation for opportunity.",
    "Flattery will go far tonight.",
    "He who laughs at himself never runs out of things to laugh at.",
    "He who laughs last is laughing at you.",
    "He who throws dirt is losing ground.",
    "Some men dream of fortunes, others dream of cookies.",
    "Someone will invite you to a Karaoke party.",
    "That wasn't chicken.",
    "There is no mistake so great as that of being always right.",
    "You love Chinese food.",
    "I am worth a fortune.",
    "You don't need strength to let go of something. What you really need is understanding.",
    "If you want the rainbow, you have to tolerate the rain.",
    "Fear is interest paid on a debt you may not owe.",
    "Hardly anyone knows how much is gained by ignoring the future.",
    "The wise man is the one that makes you think that he is dumb.",
    "The usefulness of a cup is in its emptiness.",
    "He who throws mud loses ground.",
    "Success lies in the hands of those who wants it.",
    "To avoid criticism, do nothing, say nothing, be nothing.",
    "One that would have the fruit must climb the tree.",
    "Probability of being seen directly proportional to stupidity of act.",
    "He who dies with most toys, still dies.",
    "Person who rests on laurels gets thorn in backside.",
    "Practice safe eating. Always use condiments.",
    "Person who give self-haircut after rice wine will be buzzed.",
    "Politicians are like diapers: change often, and for same reason.",
    "Atheism no fun. No holidays.",
    "Fat person not afraid of heights - afraid of widths.",
    "You have kleptomania. Take something for it.",
    "When marriage outlawed, only outlaws have in-laws.",
    "Some men dream of fortunes, others dream of cookies.",
    "The greatest danger could be your stupidity.",
    "We don't know the future, but here's a cookie.",
    "The world may be your oyster, but it doesn't mean you'll get its pearl.",
    "You will be hungry again in one hour.",
    "Don't behave with cold manners.",
    "Don't forget you are always on our minds.",
    "Fortune not found? Abort, Retry, Ignore.",
    "Help! I am being held prisoner in a fortune cookie factory.",
    "It's about time I got out of that cookie.",
    "It takes less time to do a thing right than it does to explain why you did it wrong.",
    "Big journeys begin with a single step.",
    "Of all our human resources, the most precious is the desire to improve.",
    "Do the thing you fear, and the death of fear is certain.",
    # http://www.fortunecookiemessage.com/archive.php
    "Your ability for accomplishment will follow with success.",
    "You may be hungry soon: order a takeout now.",
    "Simplicity and clearity should be the theme in your dress.",
    "A very attractive person has a message for you.",
    "Begin your life anew with strength, grace and wonder.",
    "Be most affectionate today.",
    "Spring has sprung. Life is blooming.",
    "Tomorrow Morning,Take a Left Turn As Soon As You Leave Home.",
    "Integrity is doing the right thing, even if nobody is watching.",
    "You should be able to undertake and complete anything.",
    "In evrything there is a piece of truth.But a piece.",
    "Two small jumps are sometimes better than one big leap.",
    "Did you remember to order your take out also?.",
    "Hope brings about a better future.",
    "This is really a lovely day. Congratulations!",
    "In this life it is not what we take up, but what we give up, that makes us rich.",
    "Your shoes will make you happy today.",
    "Never trouble trouble till trouble troubles you.",
    "You are the man of righteousness and integrity.",
    "Expect great things and great things will come.",
    "Out of confusion comes new patterns.",
    "Find a peaceful place where you can make plans for the future.",
    "Keep it simple. The more you say, the less people remember.",
    "Good news from afar may bring you a welcome visitor.",
    "Success is the sum of my unique visions realized by the sweat of perseverance.",
    "Love can turn cottage into a golden palace.",
    "good things take time.",
    "I have a dream....Time to go to bed.",
    "Be prepared for extra energy.",
    "Humor usually works at the moment of awkwardness.",
    "Questions provide the key to unlocking our unlimited potential.",
    "Tell them before it's too late...",
    "You have a fine capacity for the enjoyment of life.",
    "You are vigorous in words and action.",
    "You will travel to many places.",
    "How can you have a beutiful ending without making beautiful mistakes.",
    "Service is the rent we pay for the privilege of living on this planet.",
    "You can make your own happiness.",
    "A new wardrobe brings great joy and change to your life.",
    "You will be successful in your work.",
    "Laughter is the shortest distance between two people.",
    "Bread today is better than cake tomorrow.",
    "I am a bad luck person since I was born.",
    "There is always a way - if you are committed.",
    "A bird in the hand is worth three in the bush!!",
    "How can you have a beautiful ending without making beautiful mistakes?.",
    "Help, I'm prisoner in a Chinese bakery!!!",
    "The world may be your oyster, but that doesn't mean you'll get it's pearl.",
    "Nothing astonishes men so much as common sense and plain dealing.",
    "Every Friend Joys in your Success.",
    "Use your instincts now.",
    "You will have a pleasant surprise.",
    "They say you are stubborn; you call it persistence.",
    "A bargain is something you don't need at a price you can't resist.",
    "Do not seek so much to find the answer as much as to understand the question better.",
    "Man is born to live and not prepare to live.",
    "Your life becomes more and more of an adventure!",
    "You already know the answer to the questions lingering inside your head.",
    "When all else seems to fail, smile for today and just love someone.",
    "Do not upset the penguin today.",
    "There are big changes ahead for you. They will be good ones!",
    "Humor is an affirmation of dignity.",
    "You are always welcome in any gathering.",
    "It is very possible that you will achieve greatness in your lifetime.",
    "Your smile brings happiness to everyone you meet.",
    "The big issues are work, career, or status right now.",
    "Believing that you are beautiful will make you appear beautiful to others around you.",
    "Accept what comes to you each day.",
    "Affirm it, visualize it, believe it, and it`will actualize itself.",
    "Don't worry about things in the past, there is nothing you can do about them now. Don't worry about things that are happening now, make the best of a bad situation. Don't worry about things in the future, they may never happen.",
    "Your hard work will get payoff today.",
    "Bad luck and ill misfortune will infest your pathetic soul for all eternity.",
    "You don't need talent to gain experience.",
    "Give yourself some peace and quiet for at least a few hours.",
    "Don't bother looking for fault. The reward for finding it is low.",
    "Tell them what you really think. Otherwise, nothing will change.",
    "Life  always gets harder near the summit.",
    "Not all closed eye is sleeping nor open eye is seeing.",
    "There is no greater pleasure than seeing your loved ones prosper.",
    "Let the deeds speak.",
    "Ideas you believe are absurd ultimately lead to success!",
    "You will be forced to face fear, but if you do not run, fear will be afraid of you.",
    "Impossible standards just make life difficult.",
    "See if you can learn anything from the children.",
    "The most important thing in communication is to hear what isn’t being said.",
    "Listen to yourself more often.",
    "All your sorrows will vanish.",
    "today you should be a passenger. Stay close to a driver for a day.",
    "Finish your work on hand don't be greedy.",
    "You have a flair for adding a fanciful dimension to any story.",
    "Your wish will come true.",
    "Broke is only temporaryl poor is a state of mind.",
    "Help is always needed but not always appreciated. Stay true to your heart and help those in need weather they appreciate it or not.",
    "A stranger, is a friend you have not spoken to yet.",
    "The time is right to make new friends.",
    "Someone stole your fortune and replaced it with this one.  Your luck sucks.  Have a good day!",
    "IT IS NOT GOOD TO BE A USER BLESSINGS COME FROM BEING A GIVER NOT A TAKER.",
    "Bad luck and misfortune will infest your pathetic soul for all eternity.",
    "There are lessons to be learned by listening to others.",
    "If winter comes, can spring be far behind?.",
    "Accept your past without regrets. Handle your present with confidence. Face your future without fear.",
    "For success today look first to yourself.",
    "Don't lead if you won't lead.",
    "There are no limitations to the mind except those we aknowledge.",
    "Your fondest dream will come true within this year.",
    "Darkness is only succesful when there is no light. Don't forget about light!",
    "There will be a happy romance for you shortly.",
    "Follow your bliss and the Universe will open doors where there were once only walls.",
    "All your fingers can't be of the same length.",
    "Go ask your mom.",
    "All the water in the world can't sink a ship unless it gets inside.",
    "Everything happens for a reson.",
    "Your ability for accomplishment will be followed by success.",
    "Remember this: duct tape can fix anything, so don't worry about messing things up.",
    "An angry man opens his mouth and shuts up his eyes.",
    "Now these three remain, faith, hope, and love. The greatest of these is love.",
    "The smart thing to do is to begin trusting your intuitions.",
    "The best things in life aren't things.",
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "You are a person of culture.",
    "Look right...Now look left...Now look forward (do this really fast) do you feel any different? good you should feel dizzy.",
    "You are not illiterate.",
    "The joyful energy of the day will have a positive affect on you.",
    "Kiss is not a kiss without the heart.",
    "When you can't naturally feel upbeat it can sometimes help you to act as if you did.",
    "The Greatest War Sometimes Isn't On The Battlefield But Against Oneself.",
    "Great works are performed not by strength, but by perseverance.",
    "An understanding heart warms all that are graced with it's presense.",
    "You will always have good luck in your personal affairs.",
    "Those who walk in other's tracks leave no footprints.",
    "Never give up. You're not a failure if you don't give up.",
    "A new friend helps you break out of an old routine.",
    "You will soon discover a major truth about the one you love most.",
    "Encourage your peers.",
    "You will discover your hidden talents.",
    "Your succeess will astonish everyone.",
    "Your way of doing what other people do their way is what makes you special.",
    "Failure is only the opportunity to begin again more intelligently.",
    "It takes more then good memory to have good memories.",
    "A single kind work will keep one warm for years.",
    "Everything will be ok. Don't obsess. Time will prove you right, you must stay where you are.",
    "Good clothes open many doors. Go shopping.",
    "The world is always ready to receive talent with open arms.",
    "Accept yourself.",
    "When in doubt, let your instincts guide you.",
    "Fortune smiles upon you today.",
    "Before you can be reborn you must die.",
    "Some pursue happiness; you create it.",
    "The phrase is follow your dreams. Not dream period.",
    "You are about to become $8.95 poorer. ($6.95 if you had the buffet).",
    "Soon life will become more interesting.",
    "Do what is right, not what you should.",
    "Don't just spend time, invest it.",
    "The cure for grief is motion.",
    "Grant yourself a wish this year only you can do it.",
    "Those who bring sunshine to the lives of others cannot keep it from themselves.",
    "stop nagging to your partner and take it day by day.",
    "Some men dream of fortunes, others dream of cookies.",
    "Soon, a visitor shall delight you.",
    "Vision is the art of seeing what is invisible to others.",
    "It is much easier to look for the bad, than it is to find the good.",
    "Anyone who dares to be, can never be weak.",
    "When you expect your opponent to yield, you also should avoid hurting him.",
    "Aren't you glad you just had a great meal?.",
    "Acting is not lying. It is findind someone hiding inside you and letting that person run free.",
    "The wise are aware of their treasure, while fools follow their vanity.",
    "Listen to life, and you will hear the voice of life crying, Be!",
    "Enhance your karma by engaging in various charitable activities.",
    "Any decision you have to make tomorrow is a good decsion.",
    "A lifetime of happiness is in store for you.",
    "Teamwork: the fuel that allows common people attain uncommon results.",
    "Stop searching forever, happiness is just next to you.",
    "Love or money, or neither?.",
    "Your many hidden talents will become obvious to those around you.",
    "Beauty is simply beauty. originality is magical.",
    "Old friends, old wines and old gold are best.",
    "Love Is At Your Hands Be Glad And Hold On To It.",
    "Not all closed eye is sleeping, nor open eye is seeing.",
    "At this very moment you can change the rest of your life.",
    "No distance is too far, if two hearts are tied together.",
    "You will kiss your crush ohhh lalahh.",
    "You will soon witness a miracle.",
    "The important thing is to never stop questioning.",
    "You are the controller of your destiny.",
    "It's a good thing that life is not as serious as it seems to the waiter.",
    "You will be successful in love.",
    "You have a great capability to break cookies - use it wisely!",
    "Do not judge a book by it's color.",
    "All progress occurs because people dare to be different.",
    "Help, I'm being held prisoner in a  Chinese cookie factory.",
    "A virtual fortune cookie will not satisfy your hunger like that of a home made one.",
    "You are worth loving, you are also worth the effort it takes to love you.",
    "You are contemplating some action which will bring credit upon you.",
    "Only talent people get help  from others.",
    "Reading to the mind is what exercise is to the body.",
    "It's better to be alone sometimes.",
    "Keep true to the dreams of your youth.",
    "All the world may not love a lover but they will be watching him.",
    "You will be called to fill a position of high honor and responsibility.",
    "The love of your life is stepping into your planet this summer.",
    "If you want the rainbow, then you have to tolerate the rain.",
    "You will outdistance all your competitors.",
    "Q. What is H2O? A. Caring, 2 parts Hug and 1 part Open-mind.",
    "Make all you can, save all you can, give all you can.",
    "When you look down, all you see is dirt, so keep looking up.",
    "You will become better acquainted with a coworker.",
    "Movies have pause buttons, friends do not.",
    "Never quit!",
    "You have a reputation for being straightforward and honest.",
    "To determine whether someone is beautiful is not by looking at his/her appearance, but his/her heart.",
    "Others enjoy your company.",
    "You never hesitate to tackle the most difficult problems.",
    "When you can't naturally feel upbeat, it can sometimes help to act a if you did.",
    "A thrilling time is in store for you.",
    "Minor aches today are likely to pay off handsomely tomorrow.",
    "The man on the top of the mountain did not fall there.",
    "Someone close to you is waiting for you to call.",
    "It is better to have a hen tomorrow than an egg today.",
    "Love is as necessary to human beings as food and shelter.",
    "You will always be successful in your professional career.",
    "You will be hungry soon, order takeout now.",
    "Your worst enemy has a crush on you!",
    "TOO MANY PEOPLE VOLUNTEER TO CARRY THE STOOL WHEN ITS TIME TO MOVE THE PIANO.",
    "Everything will now come your way.",
    "Cooperate with those who have both know how and integrith.",
    "Sing and rejoice, fortune is smiling on you.",
    "I'm with you.",
    "Hope is like food. You will starve without it.",
    "Nothing in the world is accomplished without passion.",
    "Plan your work and work your plan.",
    "Happiness is often a rebound from hard work.",
    "Today it's up to you to create the peacefulness you long for.",
    "Cookie says, You crack me up.",
    "Meet your opponent half way. You need the exercise.",
    "Impossible is a word only to be found in the dictionary of fools.",
    "Traveling this year will bring your life into greater perspective.",
    "Good things take time.",
    "Next time you have the opportunity, go on a rollercoaster.",
    "Pray to God, but row towards shore.",
    "Instead of worrying and agonizing, move ahead constructively.",
    "Serious trouble will bypass you.",
    "Circumstance does not make the man; it reveals him to himself.",
    "See the light at the end of the tunnel.",
    "You will have a bright future.",
    "Keep your plans secret for now.",
    "Hard work pays off in the future, laziness pays off now.",
    "Excuses are easy to manufacture, and hard to sell.",
    "Friendship is an ocean that you cannot see bottom.",
    "The life of every woman or man - the heart of it - is pure and holy joy.",
    "You are one of the people who goes places in life.",
    "A merry heart does good like a medicine.",
    "傷心有多少 在乎就有多少.",
    "He who climbs a ladder must begin at the first step.",
    "Jealousy doesn't open doors, it closes them!",
    "Excellence is the difference between what I do and what I am capable of.",
    "You are offered the dream of a lifetime. Say yes!",
    "You believe in the goodness of man kind.",
    "Patience is key, a wait short or long will have its reward.",
    "Don't take yourself so seriously, no one else does.",
    "Take control of your life rather than letting things happen just like that!",
    "You've got what it takes, but it will take everything you've got!",
    "Nothing is as good or bad as it appears.",
    "Do not fear what you don't know.",
    "The days that make us happy make us wise.",
    "Life does not get better by chance. It gets better by change.",
    "You are extremely loved. Don't worry :).",
    "Sometimes you just need to lay on the floor.",
    "Joys are often the shadows, cast by sorrows.",
    "It takes more than a good memory to have good memories.",
    "Well-arranged time is the surest sign of a well-arranged mind.",
    "Never give up on someone that you don't go a day without thinking about.",
    "Perhaps you've been focusing too much on spending.",
    "Be a good friend and a fair enemy.",
    "Fortune favors the brave.",
    "You will always be surrounded by true friends.",
    "Do not follow where the path may lead.  Go where there is no path...and leave a trail.",
    "Never miss a chance to keep your mouth shut.",
    "I think, you ate your fortune while you were eating your cookie.",
    "Our deeds determine us, as much as we determine our deeds.",
    "You can open doors with your charm and patience.",
    "It's kind of fun to do the impossible.",
    "It may be those who do most, dream most.",
    "Dream lofty dreams, and as you dream, so shall you become.",
    "Tomorrow, take a moment to do something just for yourself.",
    "If your cookie still in one piece, buy lotto.",
    "Fear can keep us up all night long, but faith makes one fine pillow.",
    "A cheerful message is on its way to you.",
    "In case of fire, keep calm, pay bill and run.",
    "To forgive others one more time is to create one more blessing for yourself.",
    "It is much easier to be cirtical than to be correct.",
    "You will win success in whatever you adopt.",
    "The finest men like the finest steels have been tempered in the hottest furnace.",
    "Make a wise choice everyday.",
    "you cant go down the right path with out first discovering the path to go down.",
    "Do not worry, you will have great peace.",
    "Go with the flow will make your transition ever so much easier.",
    "Be on the lookout for coming events; They cast their shadows beforehand.",
    "A small lucky package is on its way to you soon.",
    "It's Never Too Late For Good Things To Happen!",
    "You may be disappointed if you fail, but you are doomed if you don't try.",
    "A feeling is an idea with roots.",
    "Use the force.",
    "You will enjoy good health, you will be surrounded by luxury.",
    "People in your background will be more co-operative than usual.",
    "Integrity is the essence of everything successful.",
    "If you are never patient, you will never get anything done. If you believe you can do it, you will be rewarded with success.",
    "The expanse of your intelligence is a void no universe could ever fill.",
    "There is a time to be practical now.",
    "Face facts with dignity.",
    "A good way to keep healthy is to eat more Chinese food.",
    "Bend the rod while it is still hot.",
    "A new business venture is on the horizon.",
    "The dream you've been dreaming all your life isn't worth it. Find a new dream, and once you're sure you've found it, fight for it.",
    "Live each day well and wisely.",
    "You are cautious in showing your true self to others.",
    "Share your hapiness with others today.",
    "It is better to be the hammer then the anvil.",
    "Anything you do, do it well. The last thing you want is to be sorry for what you didn't do.",
    "You will soon be surrounded by good friends and laughter.",
    "Even if the person who appears most wrong, is also quite often right.",
    "When hungry, order more Chinese food.",
    "The food here taste so good, even a cave man likes it.",
    "Never give up. Always find a reason to keep trying.",
    "We can't help everyone. But everyone can help someone.",
    "You'll advance for with your abilities.",
    "Your dream will come true when you least expect it.",
    "Forgive your enemies, but never forget them.",
    "Seek out the significance of your problem at this time.  Try to understand.",
    "Love is free. Lust will cost you everything you have.",
    "Everything will come your way.",
    "You will soon be honored by someone you respect.",
    "Men do not fail... they give up trying.",
    "You will overcome difficult times.",
    "Don't worry about the stock market. Invest in family.",
    "Many folks are about as happy as they make up their minds to be.",
    "A pleasant expeience is ahead:don't pass it by.",
    "We cannot change the direction of the wind, but we can adjust our sails.",
    "You will become great if you believe in yourself.",
    "Soon you will be sitting on top of the world.",
    "Take the chance while you still have the choice.",
    "Poverty is no disgrace.",
    "Your dearest wish will come true.",
    "Our perception and attitude toward any situation will determine the outcome.",
    "People are naturally attracted to you.",
    "A smile is your passport into the hearts of others.",
    "The worst of friends may become the best of enemies, but you will always find yourself hanging on.",
    "A wish is what makes life happen when you dream of rose petals.",
    "One of the best ways to persuade others is with your ears--by listening to them.",
    "Word to the wise: Don't play leapfrog with a unicorn.........",
    "The secret of getting ahead is getting started.",
    "You can fix it with a little extra energy and a positive attitude.",
    "A single conversation with a wise man is better than ten years of study.",
    "Life to you is a bold and dashing responsibility.",
    "The man or woman you desire feels the same about you.",
    "Nothing Shows A Man's Character More Than What He Laughs At.",
    "Your skill will accomplish what the force of many cannot.",
    "Everyone agrees you are the best.",
    "Do not be covered in sadness or be fooled in happiness they both must exist.",
    "Bad luck and misfortune will follow you all your days.",
    "You will have good luck and overcome many hardships.",
    "Enthusiastic leadership gets you a promotion when you least expect it.",
    "You cannot become rich except by enriching others.",
    "The quotes that you do not understand, are not meant for you.",
    "Those grapes you cannot taste are always sour.",
    "Here we go. Moo Shu Cereal for breakfast with duck sauce.",
    "Treasure what you have.",
    "Benefit by doing things that others give up on.",
    "Next full moon brings an enchanting evening.",
    "It's all right to have butterflies in your stomach. Just get them to fly in formation.",
    "You are very grateful for the small pleasures of life.",
    "If you have something good in your life, don't let it go!",
    "Love Conquers all.",
    "Hard words break no bones, fine words butter no parsnips.",
    "You will take a pleasant journey to a place far away.",
    "Enjoy the good luck a companion brings you.",
    "You can never been certain of success, but you can be certain of failure if you never try.",
    "What ever you're goal is in life, embrace it visualize it, and for it will be yours.",
    "Today is the tomorrow we worried about yesterday.",
    "When you get something for nothing, you just haven't been billed for it yet.",
    "A well-aimed spear is worth three.",
    "Ask yourself if what you are doing today is getting you closer to where you want to be tomorrow.",
    "True wisdom is found in happiness.",
    "You broke my cookie!",
    "If you're happy, you're successful.",
    "Enjoy yourself while you can.",
    "Your problem just got bigger. Think, what have you done.",
    "Old friends make best friends.",
    "Working out the kinks today will make for a better tomorrow.",
    "The pleasure of what we enjoy is lost by wanting more.",
    "the project on your mind will soon gain momentum.",
    "Live like you are on the bottom, even if you are on the top.",
    "You learn from your mistakes, you will learn a lot today.",
    "Difficulty at the beginning usually means ease at the end.",
    "You will prosper in the field of wacky inventions.",
    "You have an important new business development shaping up.",
    "Ganerosity will repay itself sooner than you imagine.",
    "Use your talents. That's what they are intended for.",
    "If you wish to know the mind of a man, listen to his words.",
    "There is a prospect of a thrilling time ahead for you.",
    "The energy is within you. Money is Coming!",
    "Stay to your inner-self, you will benefit in many ways.",
    "Better be the head of a chicken than the tail of an ox.",
    "Human invented language to satisfy the need to complain.",
    "You are often asked if it is in yet.",
    "You are a person of strong sense of duty.",
    "It's up to you to clearify.",
    "You will be rewarded for your patience and understanding.",
    "Your secret desire to completely change your life will manifest.",
    "Trust your intuition.",
    "All troubles you have can pass away very quickly.",
    "Enjoy life! It is better to be happy than wise.",
    "Be direct,usually one can accomplish more that way.",
    "Its amazing how much good you can do if you dont care who gets the credit.",
    "Let not your hand be stretched out to receive and shut when you should repay.",
    "AT TIMES IT IS BETTER TO KNOW WHEN EXIT THAN ENTER.",
    "A kind word will keep someone warm for years.",
    "Sometimes travel to new places leads to great transformation.",
    "Your emotional currents are flowing powerfully now.",
    "People in your surroundings will be more cooperative than usual.",
    "Let your fantasies unwind...",
    "if love someone a lot tell it before it's too late.",
    "You are never selfish with your advice or your help.",
    "Discover the power within yourself.",
    "Do not hesitate to look for help, an extra hand should always be welcomed.",
    "Elegant surroundings will soon be yours.",
    "Your future will be happy and productive.",
    "If you speak honestly, everyone will listen.",
    "Be tactful; overlook your own opportunity.",
    "Stop wishing. Start doing.",
    "Keep your eye out for someone special.",
    "There are no shortcuts to any place worth going.",
    "If your desires are not extravagant, they will be granted.",
    "Wisdom is on her way to you.",
    "To make the cart go, you must grease the wheels.",
    "Stop searching forever. Happiness is just next to you.",
    "The greatest precept is continual awareness.",
    "A focused mind is one of the most powerful forces in the universe.",
    "Prosperity makes friends and adversity tries them.",
    "A pleasant surprise is waiting for you.",
    "You are the master of every situation.",
    "Rarely do great beauty and great virtue dwell together as they do in you.",
    "You are not a person who can be ignored.",
    "It's tough to be fascinating.",
    "You will inherit a large sum of money.",
    "LIFE CONSIST NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.",
    "The secret of staying young is good health and lying about your age.",
    "Nothing seems impossible to you.",
    "Compassion is a way of being.",
    "Let's finish this up now, someone is waiting for you on that.",
    "What goes around comes around.",
    "Shoot for the moon! If you miss you will still be amongst the stars.",
    "You will always be surrounded by true friends.",
    "Luck sometimes visits a fool, but it never sits down with him.",
    "Do not think that me or my brothers have supreme control over what will happen to you.",
    "He who slithers among the ground is not always a foe.",
    "Emotion is energy in motion.",
    "Isn't there something else you should be working on right now?.",
    "The simplest answer is to act.",
    "A new wardrobe brings great joy and change in your life.",
    "The only certainty is that nothing is certain.",
    "The eyes believe themselves; the ears believe other people.",
    "You will recieve a gift from someone that cares about you.",
    "Don't worry, half the people you know are below average.",
    "A great pleasure in life is doing what others say you can't.",
    "If a person who has caused you pain and suffering has brought you, reconsider that person's value in your life.",
    "WHEN FIRE AND WATER GO TO WAR WATER ALWAYS WINS.",
    "Believing is doing.",
    "Action speaks nothing, without the Motive.",
    "Money will come to you when you are doing the right thing.",
    "You have a deep appreciation of the arts and music.",
    "Lend your money and lose your freind.",
    "A human being is a deciding being.",
    "Think of mother's exhortations more.",
    "Everything has beauty but not everyone sees it.",
    "Good beginning is half done.",
    "An alien of some sort will be appearing to you shortly!",
    "Back away from individuals who are impulsive.",
    "Everybody feels lucky for having you as a friend.",
    "Think of how you can assist on a problem, not who to blame.",
    "Hone your competitive instincts.",
    "Make the system work for you, not the other way around.",
    "Hold on to the past but eventually, let the times go and keep the memories into the present.",
    "Demonstrate refinement in everything you do.",
    "Put your unhappiness aside. Life is beautiful, be happy.",
    "Alas! The onion you are eating is someone else’s water lily.",
    "Today is an ideal time to water your parsonal garden.",
    "You are blessed, today is the day to bless others.",
    "A friend asks only for your time not your money.",
    "The measure of time to your next goal is the measure of your discipline.",
    "The cure for grief is movement.",
    "Keep your eyes open. You never know what you might see.",
    "You are what you are; understand yourself before you react.",
    "You try hard, never to fail. You don't, never to win. .",
    "Intelligence is the door to freedom and alert attention is the mother of intelligence.",
    "You only need look to your own reflection for inspiration. Because you are Beautiful!",
    "You have a deep interest in all that is artistic.",
    "A good way to stay healthy is to eat more Chinese food.",
    "Your golden opportunity is coming shortly.",
    "It is never too late. Just as it is never too early.",
    "Patience is a virtue, unless its against a brick wall.",
    "Digital circuits are made from analog parts.",
    "It is now, and in this world, that we must live.",
    "Never upset the driver of the car you're in; they're the master of your destiny until you get home.",
    "The most useless energy is trying to change what and who God so carefully created.",
    "You know where you are going and how to get there.",
    "Jealousy is a useless emotion.",
    "You have an unusually magnetic personality.",
    "Don't wait for your ship to come in, swim out to it.",
    "Great thoughts come from the heart.",
    "Someday everything will all make perfect sense.",
    "You don't need the answers to all of life's questions. Just ask your father what to do.",
    "Your ability to pick a winner will bring you success.",
    "The object of your desire comes closer.",
    "When the moment comes, take  the top one.",
    "You will plant the smallest seed and it will become the greatest and most mighty tree in the world.",
    "you will spend old age in confort and material wealth.",
    "Integrity is the essense of everything successful.",
    "Don't 'face' reality, let it be the place from which you leap.",
    "It better to be the hammer than the nail.",
    "Seize every second of your life and savor it.",
    "Birds are entangled by their feet and men by their tongues.",
    "To build a better world, start in your community.",
    "Change your thoughts and you change the world.",
    "Compassion will cure more then condemnation.",
    "A different world cannot be build by indifferent people.",
    "Be assertive when decisive action is needed.",
    "You will be called in to fulfill a position of high honor and responsibility.",
    "A clear conscience is usually the sign of a bad memory.",
    "Your life will be filled with magical moments.",
    "Failure is not defeat until you stop trying.",
    "You love Chinese food.",
    "Never bring unhappy feelings into your home.",
    "What's vice today may be virtue tomorow.",
    "You will have a long and wealthy life.",
    "Save the whales. Collect the whole set.",
    "Take it easy.",
    "An admirer is concealing his/her affection for you.",
    "You have a curious smile and a mysterious nature.",
    "Today is going to be a disasterous day, be prepared!",
    "Wise sayings often fall on barren ground, but a kind word is never thrown away.",
    "Conquer your fears or they will conquer you.",
    "You can choose, right now and in every moment, to put your powerful and effective abilities to purposeful use. There is always something you can do, no matter what the situation may be, that will move your life forward.",
    "You are thinking about doing something. Don't do it, it won't help anything.",
    "love thy neighbour, just don't get caught.",
    "Warning, do not eat your fortune.",
    "Your high-minded principles spell success.",
    "Today you shed your last tear. Tomorrow fortune knocks at your door.",
    "Virtuous find joy while Wrongdoers find grieve in their actions.",
    "Your emotional nature is strong and sensitive.",
    "About time I got out of that cookie.",
    "All the preparation you've done will finally be paying off!",
    "If everybody is a worm you should be a glow worm.",
    "Love can last a lifetime, if you want it to.",
    "You will make heads turn.",
    "You are a lover of words; One day you will write a book.",
    "Time may fly by. But Memories don't.",
    "Meeting adversity well is the source of your strength.",
    "Everyone agrees. You are the best.",
    "Do not let what you do not have prevent you from using what you do have.",
    "You will be traveling and coming into a fortune.",
    "If you are afraid to shake the dice, you will never throw a six.",
    "Failure is the mother of all success.",
    "You will soon embark on a business venture.",
    "Before the beginning of great brilliance, there must be chaos.",
    "The man who waits till tomorrow, misses the opportunities of today.",
    "You are admired by everyone for your talent and ability.",
    "It's the worst of times, you need to summon your optimism.",
    "Remember the fate of the early Worm.",
    "Consume less. Share more. Enjoy life.",
    "Now is the time to try something new.",
    "Friends long absent are coming back to you.",
    "You are a persoon with a good sense of justice, now it's time to act like it.",
    "Life is too short to waste time hating anyone.",
    "Being alone and being lonely are two different things.",
    "Love Takes Pratice.",
    "Adversity is the parent of virtue.",
    "Put your mind into planning today. Look into the future.",
    "Customer service is like taking a bath you have to keep doing it.",
    "You will soon emerge victorious from the maze you've been traveling in.",
    "You will have unexpected great good luck.",
    "The ultimate test of a relationship is to disagree but to hold hands.",
    "Land is always on the mind of a flying bird.",
    "Every day is a new day. But tomorrow is never promised.",
    "Your mouth may be moving, but nobody is listening.",
    "The race is not always to the swift, but to those who keep on running.",
    "If you never give up on love, It will never give up on you.",
    "Determination is the wake-up call to the human will.",
    "One who admires you greatly is hidden before your eyes.",
    "You  are  contemplating  some  action  which will bring credit upon you.",
    "The Wheel of Good Fortune is finally turning in your direction!",
    "Judge not according to the appearance.",
    "You are far more influential than you think.",
    "If u love someone keep fighting for them.",
    "Don't cry.",
    "What breaks in a moment may take years to mend.",
    "In music, one must think with his heart and feel with his brain.",
    "If you take a single step to your journey, you'll succeed; it's not best to fail.",
    "You will make many changes before settling down happily.",
    "Use your head, but live in your heart.",
    "To be old and wise, you must first be young and stupid.",
    "If you don’t do it excellently, don’t do it at all.",
    "Sometimes the object of the journey is not the end, but the journey itself.",
    "The earth is a school learn in it.",
    "Good health will be yours for a long time.",
    "It is not necessary to show others you have change; the change will be obvious.",
    "Dream your dream and your dream will dream of you.",
    "I hear and I forget. I see and I remember. I do and I understand.",
    "If you don t give something, you will  not get anything.",
    "Dogs have owners, cats have staff.",
    "The human spirit is stronger than anything that can happen to it.",
    "The leader seeks to communicate his vision to his followers.",
    "You love peace.",
    "The possibility of a career change is near.",
    "Life is too short to hold grudges.",
    "Your tongue is your ambassador.",
    "Your father still loves and is in always with you. Remember that.",
    "You have a quiet and unobtrusive nature.",
    "We all have extraordinary coded within us, waiting to be released.",
    "Go confidently in the direction of your dreams.",
    "Your ability to accomplish tasks will follow with success.",
    "You're true love will show himself to you under the moonlight.",
    "To affirm is to make firm.",
    "Become who you are.",
    "Keep your feet on the ground even though friends flatter you.",
    "You are not judged by your efforts you put in; you are judged on your performance.",
    "Happiness is an activity.",
    "Be patient! The Great Wall didn't got build in one day.",
    "Love will lead the way.",
    "Present your best ideas today to an eager and welcoming audience.",
    "Fear is just excitement in need of an attitude adjustment.",
    "Pick a path with heart.",
    "You are broad minded and socially active.",
    "There is someone rather annoying in your life that you need to listen to.",
    "No matter what your past has been, you have a spotless future.",
    "We are here to love each other, serve each other and uplift each other.",
    "You believe in the goodness of mankind.",
    "What ends on hope does not end at all.",
    "A man without aim is like a clock without hands, as useless if it turns as if it stands.",
    "Wow! A secret message from you teeth!",
    "You are given the chance to take part in an exciting adventure.",
    "Before trying to please others think of what makes you happy.",
    "Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.",
    "You like Chinese food.",
    "A pleasant surprise is in store for you tonight.",
    "You will have many happy days soon.",
    "Aim high, time flies.",
    "It never pays to kick a skunk.",
    "The ads revenge is massive success.",
    "I am a fortune. You just broke my little house. Where will i live now?.",
    "Old dreams never die they just get filed away.",
    "You have a strong desire for a home and your family interests come first.",
    "The time is always right to do what is right.",
    "If you refuse to accept anything but the best, you very often get it.",
    "It's never crowded along the extra mile.",
    "You will be selected for a promotion because of your accomplishments.",
    "You are talented in many ways.",
    "Everything will now come your way.",
    "Your life will prosper only if you acknowledge your faults and work to reduce them.",
    "One is not sleeping, does not mean they are awake.",
    "The problem with resisting temptation is that it may never come again.",
    "A new voyage will fill your life with untold memories.",
    "Stay true to those who would do the same for you.",
    "Oops... Wrong cookie.",
    "The troubles you have now will pass away quickly.",
    "Rivers need springs.",
    "It takes more than good memory to have good memories.",
    "Enjoyed the meal? Buy one to go too.",
    "Never cut what you can untie.",
    "May you have great luck.",
    "Rest has a peaceful effect on your physical and emotional health.",
    "Things are never quite the way they seem.",
    "Be direct, usually one can accomplish more that way.",
    "Love is on its way.",
    "Life is a dancefloor,you are the DJ!",
    "Your co-workers take pleasure in your great sense of creativity.",
    "He who climbs a ladder must begin at the first step.",
    "A man is born to live and not prepare to live.",
    "Focus in on the color yellow tomorrow for good luck!",
    "Judge each day not by the harvest you reap but by the seeds you plant.",
    "An unexpected aquaintance will resurface.",
    "Accept something that you cannot change, and you will feel better.",
    "You will achieve all your desires and pleasures.",
    "The dream is within you.",
    "Adjust finances, make budgets, to improve your standing.",
    "People who are late are often happier than those who have to wait for them.",
    "Be calm when confronting an emergency crisis.",
    "Life to you is a dashing and bold adventure.",
    "For success today, look first to yourself.",
    "You always know the right times to be assertive or to simply wait.",
    "In the eyes of lovers, everything is beautiful.",
    "Stop thinking about the road not taken and pave over the one you did.",
    "Be patient: in time, even an egg will walk.",
    "A letter of great importance may reach you any day now.",
    "Working hard will make you live a happy life.",
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "He who seeks will find.",
    "Ones always regrets what could have done. Remember for next time.",
    "Life is like a dogsled team. If you ain't the lead dog, the scenery never changes.",
    "YOUR FAILURES WILL LEAD YOU TO YOUR SUCCESS.",
    "Open up your heart - it can always be closed again.",
    "Trust your intuition. The universe is guiding your life.",
    "The love of your life is sitting across from you.",
    "Your life does not get better by chance, it gets better by change.",
    "For hate is never conquered by hate. Hate is conquered by love.",
    "A good time to finish up old tasks.",
    "While you have this day, fill it with life. While you're in this moment, give it your own special meaning and purpose and joy.",
    "You need to live authentically, and you can't ignore that.",
    "Even though it will often be difficult and complicated, you know you have what it takes to get it done.",
    "Try? No! Do or do not, there is no try.",
    "It takes ten times as many muscles to frown as it does to smile.",
    "You create enthusiasm around you.",
    "When fear hurts you, conquer it and defeat it! .",
    "You will recieve some high prize or award.",
    "If you never expect anything you can never be disappointed.",
    "A golden egg of opportunity falls into your lap this month.",
    "You will conquer obstacles to achieve success.",
    "Do not be overly judgemental of your loved one's intentions or actions.",
    "Right now there's an energy pushing you in a new direction.",
    "You create your own stage ... the audience is waiting.",
    "Your problem just became your stepping stone.  Catch the moment.",
    "A dream you have will come true.",
    "For true love? Send real roses preserved in 24kt gold!",
    "Your passions sweep you away.",
    "Get off to a new start - come out of your shell.",
    "Express yourself: Don't hold back!",
    "Whenever possible, keep it simple.",
    "Punctuality is the politeness of kings and the duty of gentle people everywhere.",
    "Life is a verb.",
    "Don't pursue happiness - create it.",
    "The best way to give credit is to give it away.",
    "You can still love what you can not have in life.",
    "Never underestimate the power of the human touch.",
    "IN ORDER TO GET THE RAINBOW, YOU MUST ENDURE THE RAIN.",
    "The greatest risk is not taking one.",
    "Think you can. Think you can't. Either way, you'll be right.",
    "You will live long and enjoy life.",
    "Truth is an unpopular subject. Because it is unquestionably correct.",
    "Wealth awaits you very soon.",
    "There are many new opportunities that are being presented to you.",
    "We cannot direct the wind but we can adjust the sails.",
    "For hate is never conquered by hate. Hate is conquered by love .",
    "An upward movement initiated in time can counteract fate.",
    "Rest is a good thing, but boredom is its brother.",
    "You are very talented in many ways.",
    "Never regret anything that made you smile.",
    "You should be able to make money and hold on to it.",
    "A new outlook brightens your image and brings new friends.",
    "You have an unusual equipment for success, use it properly.",
    "You will always get what you want through your charm and personality.",
    "Change can hurt, but it leads a path to something better.",
    "You must try, or hate yourself for not trying.",
    "Ask a friend to join you on your next voyage.",
    "When you're about to turn your heart into a stone remember: you do not walk alone.",
    "Before you wonder Am I doing things right, ask Am I doing the right things?.",
    "Patience is bitter, but its fruit is sweet.",
    "Welcome the change coming into your life.",
    "Your dearest dream is coming true. God looks after you especially.",
    "Your present question marks are going to succeed.",
    "The majority of the word can't is can.",
    "Happiness isn't something you remember, it's something you experience.",
    "Traveling more often is important for your health and happiness.",
    "You will marry your lover.",
    "You don't get harmony when everyone sings the same note.",
    "You are not a ghost.",
    "You will be sharing great news with all people you love.",
    "A short stranger will soon enter your life with blessings to share.",
    "Unleash your life force.",
    "Patience is a key to joy.",
    "If you eat a box of fortune cookies, anything is possible.",
    "Do you believe? Endurance and persistence will be rewarded.",
    "You will enjoy razon-sharp spiritual vision today.",
    "You learn from your mistakes... You will learn a lot today.",
    "Stop procrastinating - starting tomorrow.",
    "Smile. Tomorrow is another day.",
    "Let your imagination wander.",
    "A metaphor could save your life.",
    "The cooler you think you are the dumber you look.",
    "You will travel to many exotic places in your lifetime.",
    "If you want the rainbow, you have to tolerate the rain.",
    "Over self-confidence is equal to being blind.",
    "If you feel you are right, stand firmly by your convictions.",
    "You are admired for your adventuous ways.",
    "Eat something you never tried before.",
    "All comes at the proper time to him who knows how to wait.",
    "Your pain is the breaking of the shell that encloses your understanding.",
    "Our duty,as men and women,is to proceed as if limits to our ability did not exist.",
    "Your fortune is as sweet as a cookie.",
    "To courageously shoulder the responsibility of one's mistake is character.",
    "Don't find fault, find a remedy.",
    "In human endeavor, chance favors the prepared mind.",
    "It's about time you asked that special someone on a date.",
    "The gambler is like the fisherman both have beginners luck.",
    "A dream you have will come true.",
    "Being happy is not always being perfect.",
    "Land is always in the mind of the flying birds.",
    "We could learn a lot from crayons: Some of are sharp, some are pretty, some have weird names, and all are different colors. But they all have to learn to live in the same box.",
    "In God we trust.",
    "Constant grinding can turn an iron nod into a needle.",
    "To effect the quality of the day is no small achievement.",
    "If you have something worth fighting for, then fight for it.",
    "A journey of a thousand miles begins with a single step.",
    "Do what you want, when you want, and you will be rewarded.",
    "Volition, Strength, Languages, Freedom and Power rests in you.",
    "Your happiness is intertwined with your outlook on life.",
    "The one who snores will always fall asleep first.",
    "Let your heart make your decisions - it does not get as confused as your head.",
    "Happiness is not the absence of conflict, but the ability to cope with it.",
    "People enjoy having you around. Appreciate this.",
    "A big fortune will descend upon you this year.",
    "Take a minute and let it ride, then take a minute to let it breeze.",
    "You cannot love life until you live the life you love.",
    "The harder you try to not be like your parents, the more likely you will become them.",
    "Human evolution: “wider freeway but narrower viewpoints.",
    "A chance meeting opens new doors to success and friendship.",
    "If your desires are not extravagant, they will be rewarded.",
    "It is best to act with confidence, no matter how little right you have to it.",
    "A beautiful, smart, and loving person will be coming into your life.",
    "Love because it is the only true adventure.",
    "Try everything once, even the things you don't think you will like.",
    "The best prophet of the future is the past.",
    "You will be rewarded for being a good listener in the next week.",
    "The best is yet to come.",
    "Things may come to those who wait, but only the things left by those who hustle.",
    "If you love someone enough and they break your heart, you can't stop yourself from still loving them again even after all that pain.",
    "The human spirit is stronger then anything that can happen to it.",
    "Be a generous friend and a fair enemy.",
    "Happinees comes from a good life.",
    "Your dynamic eyes have attracted a secret admirer.",
    "I have a dream.... Time to go to bed.",
    "Perhaps you've been focusing too much on that one thing..",
    "An unexpected relationship will become permanent.",
    "A truly great person never puts away the simplicity of a child.",
    "you will think for yourself when you stop letting others think for you."
]
_fortunes = " ".join(_raw_fortunes)

fortunes_generator = markovify.combine(
    [
        markovify.Text(_quotes),
        markovify.Text(_fortunes)
    ],
    [   
        len(_raw_quotes),
        len(_raw_fortunes)
    ]
)